package com.pinnsights

//      "African Grey Parrot"
//      "African Ring-necked Parakeets"
//      "Cockatiel - Albino"
//      "Lovebirds - Black Masked"
//      "Blue and Gold Macaw"
//      "Lady Gouldian Finch - Blue-back"
//      "Blue Crowned Conure"
//      "Blue Indian Ringneck Parakeet"
//      "Parrotlet - Blue"
//      "Bourke's Parrot"
//      "Cockatiel"
//      "Gold Breasted Waxbill"
//      "Lady Gouldian Green Back Normal"
//      "Green Cheek Conure Normal"
//      "Green Indian Ringneck Parakeet"
//      "Green Singer (Yellow fronted canary)"
//      "Grey Indian Ringneck Parakeet"
//      "Kakarikis Cinnamon Parakeet"
//      "Lavender Waxbill"
//      "Cockatiel - Lutino"
//      "Owl Finch"
//      "Lovebirds - Peach-faced"
//      "Conure - Pineapple Green-Cheeked"
//      "Quaker Parrot (Monk Parakeet)"
//      "Red Agate Canary"
//      "Red-Billed Firefinch"
//      "Red Cheeked Cordon Bleu Finch"
//      "Red-faced Parrotfinch"
//      "Red Factor Canary"
//      "Red-Lored Amazon"
//      "Rosy Bourke's Parakeets"
//      "Severe Chestnut Fronted Macaw"
//      "Conure - Sun"
//      "Umbrella Cockatoo"
//      "Violet Indian Ringneck"
//      "White Canary"
//      "Cockatiel - White-faced"
//      "Lady Gouldian Finch - Yellow-back"
//      "Yellow Canary"
//      "Zebra Finch - Normal"